const ptr=require("./ptr");
const def=require("./def");
const note=require("./note");
const link=require("./link");
const bilink=require("./bilink");
const kepan=require("./kepan");
const figure=require("./figure");
const translation=require("./translation");
const head=require("./head");
const mppsnote=require("./mppsnote");
module.exports={ptr,def,note,link,bilink,figure,kepan,translation,head,mppsnote}